### ISSUE TITLE
Add GitHub Issue Templates

### ISSUE THREAD

**Issue by ahoefling** [FileOnQ/Imaging.Raw#15]
There is no templates for bugs/specs/pull requests. Let's add a standard template to make it easier for community members to contribute to the library

**Comment by Bett-A-Fish** [comment]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Looks like I cant add a template for issues without access to repo settings.

**Comment by mitchelsellers** [comment]
You can cheat, just add the file in the .github folder
